spring.application.name=ttsproject
spring.datasource.url=jdbc:mysql://localhost:3306/ttsdb
spring.datasource.username=root
spring.datasource.password=Aaku@2014

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect